-- begin CEUESR_DOCUMENT
alter table CEUESR_DOCUMENT add constraint FK_CEUESR_DOCUMENT_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
create index IDX_CEUESR_DOCUMENT_ON_FILE on CEUESR_DOCUMENT (FILE_ID)^
-- end CEUESR_DOCUMENT
-- begin CEUESR_BLOGPOST
alter table CEUESR_BLOGPOST add constraint FK_CEUESR_BLOGPOST_ON_WRITTEN_BY foreign key (WRITTEN_BY_ID) references SEC_USER(ID)^
create index IDX_CEUESR_BLOGPOST_ON_WRITTEN_BY on CEUESR_BLOGPOST (WRITTEN_BY_ID)^
-- end CEUESR_BLOGPOST
