alter table CEUESR_BLOGPOST add constraint FK_CEUESR_BLOGPOST_ON_WRITTEN_BY foreign key (WRITTEN_BY_ID) references SEC_USER(ID);
create index IDX_CEUESR_BLOGPOST_ON_WRITTEN_BY on CEUESR_BLOGPOST (WRITTEN_BY_ID);
